title: "Gabriel Zepeda's Portfolio"
description: "A simple portfolio for a simple man"

# Webpage Theme
theme: minima


# My Headers
header_pages:
  - index.md
  - projects.md
  - about.md
  - contacts.md
  - resume_draft.md

author:
  name: Gabriel   
  avatar: "/assests/img/headshot2.jpg"
  bio: "Cyber Security Expert with a focus on SOC Analyst foundations"
  email: AntonioSolomon1776@gmail.com

social_links:
  - { platform: github, user_url: "https://github.com/AntoTheSol/DAE-6MonthProjects/tree/main" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/gabriel-z-757404aa/"}
