# Webpage Theme
theme: minima

# My Headers
header_pages:
  - index.md
  - projects.md

author:
  name: Gabriel   
  email: AntonioSolomon1776@gmail.com

social_links:
  - { platform: github, user_url: "" }
  - { platform: linkedin, user_url: ""}
